### ISSUE TITLE
/tags/* not working

### ISSUE THREAD

**Issue by gregsramblings** [austingebauer/devise#3]
https://austingebauer.com/tags/golang/ doesn't show all posts with the "golang" tag. I'm seeing the same behavior on my site. 

Thanks!

**Comment by austingebauer** [comment]
Thanks for opening this, @gregsramblings! I'll have a look at this and try to get a fix in quickly.

**Comment by austingebauer** [comment]
@gregsramblings - This should be fixed in a5b61129d191f46cd0bf7c25c2f54faba1cdc55c. You can see what the change looks like on https://austingebauer.com/tags/ and https://austingebauer.com/tags/golang/. The tags/* page now behaves similar to the categories/* page. 

Can you update your Devise theme to the latest commit via [devise#updating](https://github.com/austingebauer/devise#updating) and let me know if that works for you? Thanks!

**Comment by gregsramblings** [comment]
All good - thanks!
