### ISSUE TITLE
no resizing of images in posts

### ISSUE THREAD

**Issue by Zeheleo** [austingebauer/devise#7]
Hi, Austin!

First of all, thank you for the convenient, fast and micro hugo theme.
but I got an one problem about posting images.

all the images I post through markdown file (.md) are posted as original image, not resized.
In your theme post (https://austingebauer.com/post/2020/devise-hugo-theme/), your 1500 * 1000 image is aligned and resized properly. Am I missing something or should I fix .css file of the theme?

here is the md line I used to post image.
`![text](/path/to/img.jpg "title")`

**Comment by austingebauer** [comment]
Thanks, @Zeheleo! I'm glad you like the theme.

I'm going to add a style to the theme so that images are sized and aligned with a better default. In the meantime, you can work around this by using HTML in the markdown. That is what I've done for the post on my website that you linked to.

You can use something like: `<img class="img-thumbnail" src="/path/to/img.jpg"/>`

**Comment by Zeheleo** [comment]
Thank you for the answer, I tried HTML and now alignment and resizing is working as I wish. Much appreciated!

**Comment by quaintdev** [comment]
@austingebauer excellent work on this theme. I love it.

I have the same issue as @Zeheleo. Is this fixed or should I be using the workaround? Thanks.

**Comment by austingebauer** [comment]
Thanks, @quaintdev! I'm glad you like the theme.

I've just fixed the default image styles in 9640df0. You should now be able to use markdown `![text](/path/to/img.jpg "title")` for images and see some reasonable default styling. Just pull the latest commit for the theme!

**Comment by quaintdev** [comment]
Works like a charm. Thanks.
